# Generated by Django 4.1.5 on 2023-12-14 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name": "Company", "verbose_name_plural": "Companies"},
        ),
    ]
