# Generated by Django 4.1.5 on 2023-12-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("OWNER", "OWNER"), ("EMPLOYEE", "EMPLOYEE")],
                default="OWNER",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
